packages:
  adios2:
    require:
    - +shared+mpi+python+sst+dataman+hdf5+zfp

  hdf5:
    require:
    - "@1.14:"
    - +shared+mpi

  parallel-netcdf:
    require:
    - +shared

  ascent:
    require:
    - +adios2+openmp+mpi+python+shared+vtkh+dray+test
    conflict:
    - "@develop"

  conduit:
    require:
    - ~hdf5_compat

  paraview:
    require:
    - any_of:
      - "@5.11"
      - "@5.12"
      - "@5.13"
    - +adios2+examples+mpi+openpmd+hdf5+python+kits+shared+catalyst+libcatalyst use_vtkm=on
    conflict:
    - "@master"

  libcatalyst:
    require:
    - +mpi

  visit:
    require:
    - +adios2+hdf5+mpi+python+silo

  vtk-m:
    require:
    - "@2:"
    - +shared+openmp+mpi+rendering+examples
